name: Release

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore ./src
    - name: Build
      run: dotnet build ./src --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src --configuration Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack ./src/SanalPosTR/SanalPosTR.csproj --configuration Release --no-build --output bin/Release/Publish
    - name: Publish to Nuget
      run: dotnet nuget push bin/Release/Publish/**/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
